### PR TITLE
use "opn" instead of "open"

### PR DESCRIPTION
**Pull request by YunfengZhao915**

### CODE REVIEW

**Comment by evalsocket** [comment]
@YunfengZhao915 what's the benefit of that PR

**Comment by YunfengZhao915** [comment]
@evalsocket 
"open" project is deprecated. In its homepage, it remmonds using "opn":
https://github.com/jjrdn/node-open
The home page of "opn" is:
https://github.com/sindresorhus/opn

**Comment by evalsocket** [comment]
Does it solve the vulnerability

**Review by yindia — APPROVED** [review]

**Comment by evalsocket** [comment]
@slunecniborecek it's hard to say. Maintainer of this repo is not much active. So for now you can create  fork from @jsoverson  repo and use grunt-open

**Comment by jsoverson** [comment]
This was published to npm.

**Comment by YunfengZhao915** [comment]
> This was published to npm.

Thanks @jsoverson

**Pull request merged**
